#!/usr/bin/env bash
set -euo pipefail

# run_renode_lvgl.sh — simulate Zephyr LVGL firmware in Renode
# Usage: ./run_renode_lvgl.sh [WORKDIR] [BOARD] [DEMO] [RESOLUTION]
# Run setup_zephyr_lvgl.sh first to build the firmware.
# DEMO and RESOLUTION must match the setup command.

WORKDIR="${1:-$HOME/zephyr-renode}"
BOARD="${2:-stm32f746g_disco}"
DEMO="${3:-hello_world}"
RESOLUTION="${4:-480x272}"
LOG="$HOME/zephyr-build.log"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

log() { echo "$*" | tee -a "$LOG"; }

if [ "$BOARD" != "stm32f746g_disco" ]; then
  log "ERROR: Unsupported board '$BOARD'. This launcher only supports stm32f746g_disco."
  exit 1
fi

case "$RESOLUTION" in
  480x272)
    BOARD_REPL="platforms/boards/stm32f7_discovery-bb.repl"
    ;;
  800x400)
    BOARD_REPL="$SCRIPT_DIR/boards/stm32f746g_disco_800x400.repl"
    ;;
  *)
    log "ERROR: Unsupported resolution '$RESOLUTION'. Choose: 480x272 or 800x400."
    exit 1
    ;;
esac

# ── Locate Renode ─────────────────────────────────────────────────────────────
find_renode() {
  for loc in \
    "$HOME/renode/renode" \
    "$HOME/.local/bin/renode" \
    "/opt/renode/renode"; do
    [ -x "$loc" ] && { echo "$loc"; return 0; }
  done
  command -v renode 2>/dev/null && return 0
  return 1
}

RENODE_BIN=$(find_renode || true)
if [ -z "$RENODE_BIN" ]; then
  log "ERROR: Renode not found. Run ./install_renode.sh first."
  exit 1
fi

# ── WSLg detection ────────────────────────────────────────────────────────────
has_wslg() {
  grep -qi microsoft /proc/version 2>/dev/null || return 1
  [ -d /mnt/wslg ] || [ -S /tmp/.X11-unix/X0 ] || \
    [ -n "${DISPLAY:-}" ] || [ -n "${WAYLAND_DISPLAY:-}" ]
}
if has_wslg; then
  RENODE_FLAGS=""
  log "Display: WSLg (GUI enabled)"
else
  RENODE_FLAGS="--disable-xwt"
  log "Display: headless (--disable-xwt)"
fi

# ── Verify firmware artifact ──────────────────────────────────────────────────
ARTIFACT="$WORKDIR/build_${BOARD}_${DEMO}_${RESOLUTION}/zephyr/zephyr.elf"
if [ ! -f "$ARTIFACT" ]; then
  log "ERROR: Firmware not found at $ARTIFACT"
  log "       Run: ./setup_zephyr_lvgl.sh $WORKDIR $BOARD $DEMO $RESOLUTION"
  exit 1
fi

log "Resolution: $RESOLUTION"
log "Firmware  : $ARTIFACT"
log "Platform  : $BOARD_REPL"

# ── Generate the resolution-specific Renode script ─────────────────
RENODE_RESC="$WORKDIR/run_${BOARD}_${DEMO}_${RESOLUTION}.resc"
if [ ! -f "$RENODE_RESC" ] || [ "$ARTIFACT" -nt "$RENODE_RESC" ] || \
   [ "${BASH_SOURCE[0]}" -nt "$RENODE_RESC" ]; then
  log "Writing Renode script: $RENODE_RESC"
  cat > "$RENODE_RESC" <<RESC_EOF
# Renode script for ${BOARD} at ${RESOLUTION}
# Generated by run_renode_lvgl.sh — demo: ${DEMO}. Re-run the script to regenerate.

using sysbus

mach create "${BOARD}"
machine LoadPlatformDescription @${BOARD_REPL}

sysbus LoadELF @${ARTIFACT}

showAnalyzer sysbus.usart1
showAnalyzer "display" sysbus.ltdc
start
RESC_EOF
fi

# ── Launch Renode ─────────────────────────────────────────────────────────────
log "Starting Renode: $RENODE_BIN ${RENODE_FLAGS:-(GUI)} → $RENODE_RESC"
# shellcheck disable=SC2086  # word-split of RENODE_FLAGS is intentional
exec "$RENODE_BIN" $RENODE_FLAGS -e "i @${RENODE_RESC}; start"
